version: '3'

services:
  web:
    build: .
    container_name: todo-app
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
